name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'master'

jobs:
  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    name: Test (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        elixir: ['1.12', '1.11', '1.10']
        # All of the above can use this version. For details see: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        otp: [24, 23, 22]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
			- run: |
        	if [ ! -d "stripe-mock/stripe-mock_${0.95.0}" ]; then
        mkdir -p stripe-mock/stripe-mock_${0.95.0}/
        curl -L "https://github.com/stripe/stripe-mock/releases/download/v${0.95.0}/stripe-mock_${0.95.0}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${0.95.0}_linux_amd64.tar.gz"
        tar -zxf "stripe-mock/stripe-mock_${0.95.0}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
          fi
      - run: mix deps.get
      - run: mix test

  lint:
    runs-on: ubuntu-latest
    name: Linting
    strategy:
      matrix:
        elixir: ['1.12']
        # All of the above can use this version. For details see: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        otp: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        env:
          cache-name: mix
        with:
          path: ~/.mix
          key: cache-${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
          restore-keys: |
             cache-${{ runner.os }}-${{ env.cache-name }}-
      - uses: actions/cache@v1
        env:
          cache-name: build
        with:
          path: _build
          key: cache-${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
          restore-keys: |
             cache-${{ runner.os }}-${{ env.cache-name }}-
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix dialyzer --halt-exit-status
